server:
  port: 8080
spring:
  application:
    name: luke_blog

  datasource:
    url: jdbc:mysql://localhost:3306/luke_blog
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver