#配置项
#端口
luke.blog.server.port: 8079
#项目地址
luke.blog.application.name: '/luke_blog'
#JDBC
luke.blog.jdbc.username: root
luke.blog.jdbc.password: root
#本地
luke.blog.jdbc.url: jdbc:mysql://localhost:3306/luke_blog?charterEncoding=UTF-8&userSSL=false
#服务器
#luke.blog.jdbc.url: url:jdbc:mysql://39.99.188.50:3306/luke_blog?charterEncoding=UTF-8&userSSL=false
#redis
luke.blog.redis.port: 6379
luke.blog.redis.host: 39.99.188.50
luke.blog.redis.password: 123456
#图片保存路径
#windows
#luke.blog.image.save-path: F:\ProjectsFolder\IdeaProjects\images
#linux
luke.blog.image.save-path: /usr/local/springboot/images
#图片大小限制 2MB
luke.blog.image.max-size: 2097152
#Cookie domain
luke.blog.cookie.domain: '39.99.188.50'


server:
  port: ${luke.blog.server.port}
  servlet:
    context-path: ${luke.blog.application.name}
spring:
  application:
    name: ${luke.blog.application.name}
  datasource:
    username: ${luke.blog.jdbc.username}
    password: ${luke.blog.jdbc.password}
    driver-class-name: com.mysql.jdbc.Driver
    url: ${luke.blog.jdbc.url}
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  redis:
    host: ${luke.blog.redis.host}
    port: ${luke.blog.redis.port}
    password: ${luke.blog.redis.password}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.luke.luke_blog.dao: debug

pagehelper:
  helper-dialect: mysql



